
services:
  postgres:
    image: postgres:15
    container_name: strapi-postgres
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: strapi_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    image: strapi/strapi:latest
    container_name: strapi-app
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_password
      APP_KEYS: some-random-key
      API_TOKEN_SALT: some-random-salt
      ADMIN_JWT_SECRET: some-random-admin-jwt-secret
      JWT_SECRET: some-random-jwt-secret
    volumes:
      - ./my-app:/app

    ports:
      - "1337:1337"  # Internal port (not needed for nginx, optional)
    networks:
      - strapi-net

  nginx:
    image: nginx:latest
    container_name: strapi-nginx
    depends_on:
      - strapi
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - strapi-net

volumes:
  postgres-data:
  strapi-data:

networks:
  strapi-net:
    external: true

