name: CI - Build & Push Strapi Image

on:
  push:
    branches: [ onkar_lonkar ]

env:
  IMAGE_REPO: onkarlonkar9/strapi-prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch if needed)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine tag (short SHA + date)
        id: tag
        run: |
          SHORT_SHA=${GITHUB_SHA::8}
          DATE=$(date -u +"%Y%m%dT%H%M%SZ")
          IMAGE_TAG="${DATE}-${SHORT_SHA}"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        if: secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_PASSWORD
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ steps.tag.outputs.image_tag }}
            ${{ env.IMAGE_REPO }}:latest

      - name: Set image_tag output
        id: set_tag
        run: |
          echo "::set-output name=image_tag::${{ steps.tag.outputs.image_tag }}"
